apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: megatest03-poi-map-app-dev
  annotations:
    argocd/app-name: megatest03-poi-map-app-dev
    backstage.io/kubernetes-id: megatest03-poi-map-app
    backstage.io/kubernetes-namespace: megatest03
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/megatest03-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/megatest03/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/megatest03/deployments/megatest03-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/megatest03-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://megatest03-poi-map-app-megatest03.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/megatest03"
  system: workshop-system-megatest03
  consumesApis:
    - gateway-api-megatest03
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-megatest03
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/megatest03"
